### ISSUE TITLE
Pan gestures do not respond

### ISSUE THREAD

**Issue by gaetanzanella** [faberNovel/DynamicOverlay#2]
```swift
struct ContentView: View {

    var body: some View {
            List { // does not scroll
                Text("Ahaha")
            }
            .dynamicOverlay(Color.green)
    }
}
```

**Comment by maggnus** [comment]
How to fix?

**Comment by matthewcheok** [comment]
It looks like touches are getting eaten by this view `_TtGC7SwiftUI16PlatformViewHostGVS_42PlatformViewControllerRepresentableAdaptorV14DynamicOverlay38OverlayContainerRepresentableAdaptator__`. It looks like a view generated by SwiftUI.

**Comment by matthewcheok** [comment]
I think this is a view that's automatically created because `OverlayContainerRepresentableAdaptator` is `UIViewControllerRepresentable` and it might be challenging to have it passthrough touch events. The only solution I can think is creating a container view controller in UIKit that composes both the overlay and the background content (to avoid this issue) and wrap in a SwiftUI view using `UIViewControllerRepresentable`.
